// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: testdata/gentest/only_unary_query.proto

package gentest

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"

	//protoc-gen-map packages
	bytes "bytes"
	context "context"
	sql "database/sql"
	mapper "github.com/jackskj/protoc-gen-map/mapper"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	log "log"
	sync "sync"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Code generated by protoc-gen-map. DO NOT EDIT.
// To Use:
// 1. Instantiate MapperServers with sql.DB connection
// 2. Register MapperServer as the gRPC service server
// 3. Begin serving

type OnlyQuryServiceMapServer struct {
	DB          *sql.DB
	QueryMapper *mapper.Mapper

	mapperGenMux sync.Mutex
}

func (m *OnlyQuryServiceMapServer) Query(ctx context.Context, r *OnlyQury) (*OnlyQury, error) {
	sqlBuffer := &bytes.Buffer{}
	if err := sqlTemplate.ExecuteTemplate(sqlBuffer, "Query", r); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	rawSql := sqlBuffer.String()

	rows, err := m.DB.Query(rawSql)
	defer rows.Close()
	if err != nil {
		log.Printf("error executing query.\n OnlyQury request: %s \n,query: %s \n error: %s", r, rawSql, err)
		return nil, status.Error(codes.InvalidArgument, "request generated malformed query")
	}
	if m.QueryMapper == nil {
		m.mapperGenMux.Lock()
		m.QueryMapper, err = mapper.New(rows, &OnlyQury{})
		m.mapperGenMux.Unlock()
		if err != nil {
			log.Printf("error generating QueryMapper: %s", err)
			return nil, status.Error(codes.Internal, "error generating OnlyQury mapping")
		}
		m.QueryMapper.Log()
	}
	respMap := m.QueryMapper.NewResponseMapping()
	if err := m.QueryMapper.GetValues(rows, respMap); err != nil {
		log.Printf("error loading data for Query: %s", err)
		return nil, status.Error(codes.Internal, "error loading data")
	}
	if err := m.QueryMapper.MapResponse(respMap); err != nil {
		log.Printf("error mappig QueryMapper: %s", err)
		m.QueryMapper.Error = nil
		return nil, status.Error(codes.Internal, "error mappig OnlyQury")
	}
	m.QueryMapper.Log()
	if len(respMap.Responses) == 0 {
		//No Responses found
		return new(OnlyQury), nil
	} else {
		return respMap.Responses[0].(*OnlyQury), nil
	}

}
