// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: testdata/gentest/only_unary_query.proto

package gentest

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OnlyQury struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlyQury) Reset() {
	*x = OnlyQury{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_gentest_only_unary_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlyQury) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlyQury) ProtoMessage() {}

func (x *OnlyQury) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_gentest_only_unary_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlyQury.ProtoReflect.Descriptor instead.
func (*OnlyQury) Descriptor() ([]byte, []int) {
	return file_testdata_gentest_only_unary_query_proto_rawDescGZIP(), []int{0}
}

var File_testdata_gentest_only_unary_query_proto protoreflect.FileDescriptor

var file_testdata_gentest_only_unary_query_proto_rawDesc = []byte{
	0x0a, 0x27, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x65, 0x6e, 0x74, 0x65,
	0x73, 0x74, 0x2f, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x65, 0x6e, 0x74, 0x65,
	0x73, 0x74, 0x22, 0x0a, 0x0a, 0x08, 0x4f, 0x6e, 0x6c, 0x79, 0x51, 0x75, 0x72, 0x79, 0x32, 0x42,
	0x0a, 0x0f, 0x4f, 0x6e, 0x6c, 0x79, 0x51, 0x75, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2f, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x11, 0x2e, 0x67, 0x65, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x6e, 0x6c, 0x79, 0x51, 0x75, 0x72, 0x79, 0x1a, 0x11, 0x2e,
	0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x6e, 0x6c, 0x79, 0x51, 0x75, 0x72, 0x79,
	0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6a, 0x61, 0x63, 0x6b, 0x73, 0x6b, 0x6a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x6d, 0x61, 0x70, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x2f, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x3b, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testdata_gentest_only_unary_query_proto_rawDescOnce sync.Once
	file_testdata_gentest_only_unary_query_proto_rawDescData = file_testdata_gentest_only_unary_query_proto_rawDesc
)

func file_testdata_gentest_only_unary_query_proto_rawDescGZIP() []byte {
	file_testdata_gentest_only_unary_query_proto_rawDescOnce.Do(func() {
		file_testdata_gentest_only_unary_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdata_gentest_only_unary_query_proto_rawDescData)
	})
	return file_testdata_gentest_only_unary_query_proto_rawDescData
}

var file_testdata_gentest_only_unary_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testdata_gentest_only_unary_query_proto_goTypes = []interface{}{
	(*OnlyQury)(nil), // 0: gentest.OnlyQury
}
var file_testdata_gentest_only_unary_query_proto_depIdxs = []int32{
	0, // 0: gentest.OnlyQuryService.Query:input_type -> gentest.OnlyQury
	0, // 1: gentest.OnlyQuryService.Query:output_type -> gentest.OnlyQury
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_gentest_only_unary_query_proto_init() }
func file_testdata_gentest_only_unary_query_proto_init() {
	if File_testdata_gentest_only_unary_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdata_gentest_only_unary_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlyQury); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdata_gentest_only_unary_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testdata_gentest_only_unary_query_proto_goTypes,
		DependencyIndexes: file_testdata_gentest_only_unary_query_proto_depIdxs,
		MessageInfos:      file_testdata_gentest_only_unary_query_proto_msgTypes,
	}.Build()
	File_testdata_gentest_only_unary_query_proto = out.File
	file_testdata_gentest_only_unary_query_proto_rawDesc = nil
	file_testdata_gentest_only_unary_query_proto_goTypes = nil
	file_testdata_gentest_only_unary_query_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OnlyQuryServiceClient is the client API for OnlyQuryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnlyQuryServiceClient interface {
	Query(ctx context.Context, in *OnlyQury, opts ...grpc.CallOption) (*OnlyQury, error)
}

type onlyQuryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnlyQuryServiceClient(cc grpc.ClientConnInterface) OnlyQuryServiceClient {
	return &onlyQuryServiceClient{cc}
}

func (c *onlyQuryServiceClient) Query(ctx context.Context, in *OnlyQury, opts ...grpc.CallOption) (*OnlyQury, error) {
	out := new(OnlyQury)
	err := c.cc.Invoke(ctx, "/gentest.OnlyQuryService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnlyQuryServiceServer is the server API for OnlyQuryService service.
type OnlyQuryServiceServer interface {
	Query(context.Context, *OnlyQury) (*OnlyQury, error)
}

// UnimplementedOnlyQuryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOnlyQuryServiceServer struct {
}

func (*UnimplementedOnlyQuryServiceServer) Query(context.Context, *OnlyQury) (*OnlyQury, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterOnlyQuryServiceServer(s *grpc.Server, srv OnlyQuryServiceServer) {
	s.RegisterService(&_OnlyQuryService_serviceDesc, srv)
}

func _OnlyQuryService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlyQury)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlyQuryServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gentest.OnlyQuryService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlyQuryServiceServer).Query(ctx, req.(*OnlyQury))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnlyQuryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gentest.OnlyQuryService",
	HandlerType: (*OnlyQuryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _OnlyQuryService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testdata/gentest/only_unary_query.proto",
}
