// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata/gentest/only_unary_query.proto

package gentest

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OnlyQury struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlyQury) Reset()         { *m = OnlyQury{} }
func (m *OnlyQury) String() string { return proto.CompactTextString(m) }
func (*OnlyQury) ProtoMessage()    {}
func (*OnlyQury) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba37bcd3d7cf6693, []int{0}
}

func (m *OnlyQury) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlyQury.Unmarshal(m, b)
}
func (m *OnlyQury) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlyQury.Marshal(b, m, deterministic)
}
func (m *OnlyQury) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlyQury.Merge(m, src)
}
func (m *OnlyQury) XXX_Size() int {
	return xxx_messageInfo_OnlyQury.Size(m)
}
func (m *OnlyQury) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlyQury.DiscardUnknown(m)
}

var xxx_messageInfo_OnlyQury proto.InternalMessageInfo

func init() {
	proto.RegisterType((*OnlyQury)(nil), "gentest.OnlyQury")
}

func init() {
	proto.RegisterFile("testdata/gentest/only_unary_query.proto", fileDescriptor_ba37bcd3d7cf6693)
}

var fileDescriptor_ba37bcd3d7cf6693 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2f, 0x49, 0x2d, 0x2e,
	0x49, 0x49, 0x2c, 0x49, 0xd4, 0x4f, 0x4f, 0xcd, 0x03, 0xb1, 0xf5, 0xf3, 0xf3, 0x72, 0x2a, 0xe3,
	0x4b, 0xf3, 0x12, 0x8b, 0x2a, 0xe3, 0x0b, 0x4b, 0x53, 0x8b, 0x2a, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0xd8, 0xa1, 0xf2, 0x4a, 0x5c, 0x5c, 0x1c, 0xfe, 0x79, 0x39, 0x95, 0x81, 0xa5, 0x45,
	0x95, 0x46, 0x4e, 0x5c, 0xfc, 0x30, 0x76, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x3e,
	0x17, 0x6b, 0x20, 0x48, 0x9b, 0x90, 0xa0, 0x1e, 0x54, 0x87, 0x1e, 0x4c, 0x89, 0x14, 0xa6, 0x90,
	0x12, 0x83, 0x93, 0x4d, 0x94, 0x55, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae,
	0x7e, 0x56, 0x62, 0x72, 0x76, 0x71, 0x76, 0x96, 0x3e, 0xd8, 0xd2, 0x64, 0xdd, 0xf4, 0xd4, 0x3c,
	0xdd, 0xdc, 0xc4, 0x02, 0x7d, 0x74, 0x57, 0x5a, 0x43, 0xe9, 0x24, 0x36, 0xb0, 0x42, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xbe, 0xd2, 0x05, 0xc8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OnlyQuryServiceClient is the client API for OnlyQuryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnlyQuryServiceClient interface {
	Query(ctx context.Context, in *OnlyQury, opts ...grpc.CallOption) (*OnlyQury, error)
}

type onlyQuryServiceClient struct {
	cc *grpc.ClientConn
}

func NewOnlyQuryServiceClient(cc *grpc.ClientConn) OnlyQuryServiceClient {
	return &onlyQuryServiceClient{cc}
}

func (c *onlyQuryServiceClient) Query(ctx context.Context, in *OnlyQury, opts ...grpc.CallOption) (*OnlyQury, error) {
	out := new(OnlyQury)
	err := c.cc.Invoke(ctx, "/gentest.OnlyQuryService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnlyQuryServiceServer is the server API for OnlyQuryService service.
type OnlyQuryServiceServer interface {
	Query(context.Context, *OnlyQury) (*OnlyQury, error)
}

// UnimplementedOnlyQuryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOnlyQuryServiceServer struct {
}

func (*UnimplementedOnlyQuryServiceServer) Query(ctx context.Context, req *OnlyQury) (*OnlyQury, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterOnlyQuryServiceServer(s *grpc.Server, srv OnlyQuryServiceServer) {
	s.RegisterService(&_OnlyQuryService_serviceDesc, srv)
}

func _OnlyQuryService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlyQury)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlyQuryServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gentest.OnlyQuryService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlyQuryServiceServer).Query(ctx, req.(*OnlyQury))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnlyQuryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gentest.OnlyQuryService",
	HandlerType: (*OnlyQuryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _OnlyQuryService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testdata/gentest/only_unary_query.proto",
}
