// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: testdata/gentest/unary_type_test.proto

package gentest

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_testdata_gentest_unary_type_test_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_testdata_gentest_unary_type_test_proto_rawDescGZIP(), []int{1}
}

type EMpTyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EMpTyResponse) Reset() {
	*x = EMpTyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EMpTyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMpTyResponse) ProtoMessage() {}

func (x *EMpTyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMpTyResponse.ProtoReflect.Descriptor instead.
func (*EMpTyResponse) Descriptor() ([]byte, []int) {
	return file_testdata_gentest_unary_type_test_proto_rawDescGZIP(), []int{2}
}

type NilResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NilResponse) Reset() {
	*x = NilResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NilResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NilResponse) ProtoMessage() {}

func (x *NilResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NilResponse.ProtoReflect.Descriptor instead.
func (*NilResponse) Descriptor() ([]byte, []int) {
	return file_testdata_gentest_unary_type_test_proto_rawDescGZIP(), []int{3}
}

type NullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullResponse) Reset() {
	*x = NullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullResponse) ProtoMessage() {}

func (x *NullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullResponse.ProtoReflect.Descriptor instead.
func (*NullResponse) Descriptor() ([]byte, []int) {
	return file_testdata_gentest_unary_type_test_proto_rawDescGZIP(), []int{4}
}

type NuLlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NuLlResponse) Reset() {
	*x = NuLlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NuLlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NuLlResponse) ProtoMessage() {}

func (x *NuLlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NuLlResponse.ProtoReflect.Descriptor instead.
func (*NuLlResponse) Descriptor() ([]byte, []int) {
	return file_testdata_gentest_unary_type_test_proto_rawDescGZIP(), []int{5}
}

type SampleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SampleResponse) Reset() {
	*x = SampleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleResponse) ProtoMessage() {}

func (x *SampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_gentest_unary_type_test_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleResponse.ProtoReflect.Descriptor instead.
func (*SampleResponse) Descriptor() ([]byte, []int) {
	return file_testdata_gentest_unary_type_test_proto_rawDescGZIP(), []int{6}
}

var File_testdata_gentest_unary_type_test_proto protoreflect.FileDescriptor

var file_testdata_gentest_unary_type_test_proto_rawDesc = []byte{
	0x0a, 0x26, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x65, 0x6e, 0x74, 0x65,
	0x73, 0x74, 0x2f, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73,
	0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x4d, 0x70, 0x54, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x4e, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x6e, 0x75, 0x4c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xac, 0x04, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x54, 0x79, 0x70,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63,
	0x4f, 0x6e, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x65, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x54, 0x77, 0x6f, 0x12,
	0x15, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x45, 0x4d, 0x70, 0x54, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3a, 0x0a, 0x09, 0x45, 0x78, 0x65, 0x63, 0x54, 0x68, 0x72, 0x65, 0x65, 0x12, 0x15, 0x2e,
	0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4e,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x08,
	0x45, 0x78, 0x65, 0x63, 0x46, 0x6f, 0x75, 0x72, 0x12, 0x15, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x08, 0x45, 0x78, 0x65, 0x63,
	0x46, 0x69, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x65,
	0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x6e, 0x75, 0x4c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x06, 0x49, 0x6e, 0x53, 0x65, 0x52, 0x74, 0x12, 0x15,
	0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3a, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x65, 0x6e, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x06, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67,
	0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x15, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6a, 0x61, 0x63, 0x6b, 0x73, 0x6b, 0x6a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6d, 0x61, 0x70, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74,
	0x61, 0x2f, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x3b, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x73,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testdata_gentest_unary_type_test_proto_rawDescOnce sync.Once
	file_testdata_gentest_unary_type_test_proto_rawDescData = file_testdata_gentest_unary_type_test_proto_rawDesc
)

func file_testdata_gentest_unary_type_test_proto_rawDescGZIP() []byte {
	file_testdata_gentest_unary_type_test_proto_rawDescOnce.Do(func() {
		file_testdata_gentest_unary_type_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdata_gentest_unary_type_test_proto_rawDescData)
	})
	return file_testdata_gentest_unary_type_test_proto_rawDescData
}

var file_testdata_gentest_unary_type_test_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_testdata_gentest_unary_type_test_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),   // 0: gentest.EmptyRequest
	(*EmptyResponse)(nil),  // 1: gentest.EmptyResponse
	(*EMpTyResponse)(nil),  // 2: gentest.EMpTyResponse
	(*NilResponse)(nil),    // 3: gentest.NilResponse
	(*NullResponse)(nil),   // 4: gentest.NullResponse
	(*NuLlResponse)(nil),   // 5: gentest.nuLlResponse
	(*SampleResponse)(nil), // 6: gentest.SampleResponse
}
var file_testdata_gentest_unary_type_test_proto_depIdxs = []int32{
	0, // 0: gentest.ExecTypeService.ExecOne:input_type -> gentest.EmptyRequest
	0, // 1: gentest.ExecTypeService.ExecTwo:input_type -> gentest.EmptyRequest
	0, // 2: gentest.ExecTypeService.ExecThree:input_type -> gentest.EmptyRequest
	0, // 3: gentest.ExecTypeService.ExecFour:input_type -> gentest.EmptyRequest
	0, // 4: gentest.ExecTypeService.ExecFive:input_type -> gentest.EmptyRequest
	0, // 5: gentest.ExecTypeService.InSeRt:input_type -> gentest.EmptyRequest
	0, // 6: gentest.ExecTypeService.Delete:input_type -> gentest.EmptyRequest
	0, // 7: gentest.ExecTypeService.Update:input_type -> gentest.EmptyRequest
	0, // 8: gentest.ExecTypeService.Create:input_type -> gentest.EmptyRequest
	1, // 9: gentest.ExecTypeService.ExecOne:output_type -> gentest.EmptyResponse
	2, // 10: gentest.ExecTypeService.ExecTwo:output_type -> gentest.EMpTyResponse
	3, // 11: gentest.ExecTypeService.ExecThree:output_type -> gentest.NilResponse
	4, // 12: gentest.ExecTypeService.ExecFour:output_type -> gentest.NullResponse
	5, // 13: gentest.ExecTypeService.ExecFive:output_type -> gentest.nuLlResponse
	1, // 14: gentest.ExecTypeService.InSeRt:output_type -> gentest.EmptyResponse
	6, // 15: gentest.ExecTypeService.Delete:output_type -> gentest.SampleResponse
	6, // 16: gentest.ExecTypeService.Update:output_type -> gentest.SampleResponse
	6, // 17: gentest.ExecTypeService.Create:output_type -> gentest.SampleResponse
	9, // [9:18] is the sub-list for method output_type
	0, // [0:9] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_gentest_unary_type_test_proto_init() }
func file_testdata_gentest_unary_type_test_proto_init() {
	if File_testdata_gentest_unary_type_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdata_gentest_unary_type_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_gentest_unary_type_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_gentest_unary_type_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EMpTyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_gentest_unary_type_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NilResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_gentest_unary_type_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_gentest_unary_type_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NuLlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_gentest_unary_type_test_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdata_gentest_unary_type_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testdata_gentest_unary_type_test_proto_goTypes,
		DependencyIndexes: file_testdata_gentest_unary_type_test_proto_depIdxs,
		MessageInfos:      file_testdata_gentest_unary_type_test_proto_msgTypes,
	}.Build()
	File_testdata_gentest_unary_type_test_proto = out.File
	file_testdata_gentest_unary_type_test_proto_rawDesc = nil
	file_testdata_gentest_unary_type_test_proto_goTypes = nil
	file_testdata_gentest_unary_type_test_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExecTypeServiceClient is the client API for ExecTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExecTypeServiceClient interface {
	ExecOne(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	ExecTwo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EMpTyResponse, error)
	ExecThree(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*NilResponse, error)
	ExecFour(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*NullResponse, error)
	ExecFive(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*NuLlResponse, error)
	InSeRt(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Delete(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SampleResponse, error)
	Update(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SampleResponse, error)
	Create(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SampleResponse, error)
}

type execTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecTypeServiceClient(cc grpc.ClientConnInterface) ExecTypeServiceClient {
	return &execTypeServiceClient{cc}
}

func (c *execTypeServiceClient) ExecOne(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gentest.ExecTypeService/ExecOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execTypeServiceClient) ExecTwo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EMpTyResponse, error) {
	out := new(EMpTyResponse)
	err := c.cc.Invoke(ctx, "/gentest.ExecTypeService/ExecTwo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execTypeServiceClient) ExecThree(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*NilResponse, error) {
	out := new(NilResponse)
	err := c.cc.Invoke(ctx, "/gentest.ExecTypeService/ExecThree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execTypeServiceClient) ExecFour(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*NullResponse, error) {
	out := new(NullResponse)
	err := c.cc.Invoke(ctx, "/gentest.ExecTypeService/ExecFour", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execTypeServiceClient) ExecFive(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*NuLlResponse, error) {
	out := new(NuLlResponse)
	err := c.cc.Invoke(ctx, "/gentest.ExecTypeService/ExecFive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execTypeServiceClient) InSeRt(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/gentest.ExecTypeService/InSeRt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execTypeServiceClient) Delete(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SampleResponse, error) {
	out := new(SampleResponse)
	err := c.cc.Invoke(ctx, "/gentest.ExecTypeService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execTypeServiceClient) Update(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SampleResponse, error) {
	out := new(SampleResponse)
	err := c.cc.Invoke(ctx, "/gentest.ExecTypeService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *execTypeServiceClient) Create(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SampleResponse, error) {
	out := new(SampleResponse)
	err := c.cc.Invoke(ctx, "/gentest.ExecTypeService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecTypeServiceServer is the server API for ExecTypeService service.
type ExecTypeServiceServer interface {
	ExecOne(context.Context, *EmptyRequest) (*EmptyResponse, error)
	ExecTwo(context.Context, *EmptyRequest) (*EMpTyResponse, error)
	ExecThree(context.Context, *EmptyRequest) (*NilResponse, error)
	ExecFour(context.Context, *EmptyRequest) (*NullResponse, error)
	ExecFive(context.Context, *EmptyRequest) (*NuLlResponse, error)
	InSeRt(context.Context, *EmptyRequest) (*EmptyResponse, error)
	Delete(context.Context, *EmptyRequest) (*SampleResponse, error)
	Update(context.Context, *EmptyRequest) (*SampleResponse, error)
	Create(context.Context, *EmptyRequest) (*SampleResponse, error)
}

// UnimplementedExecTypeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExecTypeServiceServer struct {
}

func (*UnimplementedExecTypeServiceServer) ExecOne(context.Context, *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecOne not implemented")
}
func (*UnimplementedExecTypeServiceServer) ExecTwo(context.Context, *EmptyRequest) (*EMpTyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecTwo not implemented")
}
func (*UnimplementedExecTypeServiceServer) ExecThree(context.Context, *EmptyRequest) (*NilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecThree not implemented")
}
func (*UnimplementedExecTypeServiceServer) ExecFour(context.Context, *EmptyRequest) (*NullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecFour not implemented")
}
func (*UnimplementedExecTypeServiceServer) ExecFive(context.Context, *EmptyRequest) (*NuLlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecFive not implemented")
}
func (*UnimplementedExecTypeServiceServer) InSeRt(context.Context, *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InSeRt not implemented")
}
func (*UnimplementedExecTypeServiceServer) Delete(context.Context, *EmptyRequest) (*SampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedExecTypeServiceServer) Update(context.Context, *EmptyRequest) (*SampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedExecTypeServiceServer) Create(context.Context, *EmptyRequest) (*SampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterExecTypeServiceServer(s *grpc.Server, srv ExecTypeServiceServer) {
	s.RegisterService(&_ExecTypeService_serviceDesc, srv)
}

func _ExecTypeService_ExecOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecTypeServiceServer).ExecOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gentest.ExecTypeService/ExecOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecTypeServiceServer).ExecOne(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecTypeService_ExecTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecTypeServiceServer).ExecTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gentest.ExecTypeService/ExecTwo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecTypeServiceServer).ExecTwo(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecTypeService_ExecThree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecTypeServiceServer).ExecThree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gentest.ExecTypeService/ExecThree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecTypeServiceServer).ExecThree(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecTypeService_ExecFour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecTypeServiceServer).ExecFour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gentest.ExecTypeService/ExecFour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecTypeServiceServer).ExecFour(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecTypeService_ExecFive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecTypeServiceServer).ExecFive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gentest.ExecTypeService/ExecFive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecTypeServiceServer).ExecFive(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecTypeService_InSeRt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecTypeServiceServer).InSeRt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gentest.ExecTypeService/InSeRt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecTypeServiceServer).InSeRt(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecTypeService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecTypeServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gentest.ExecTypeService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecTypeServiceServer).Delete(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecTypeService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecTypeServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gentest.ExecTypeService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecTypeServiceServer).Update(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecTypeService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecTypeServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gentest.ExecTypeService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecTypeServiceServer).Create(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExecTypeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gentest.ExecTypeService",
	HandlerType: (*ExecTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecOne",
			Handler:    _ExecTypeService_ExecOne_Handler,
		},
		{
			MethodName: "ExecTwo",
			Handler:    _ExecTypeService_ExecTwo_Handler,
		},
		{
			MethodName: "ExecThree",
			Handler:    _ExecTypeService_ExecThree_Handler,
		},
		{
			MethodName: "ExecFour",
			Handler:    _ExecTypeService_ExecFour_Handler,
		},
		{
			MethodName: "ExecFive",
			Handler:    _ExecTypeService_ExecFive_Handler,
		},
		{
			MethodName: "InSeRt",
			Handler:    _ExecTypeService_InSeRt_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ExecTypeService_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ExecTypeService_Update_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ExecTypeService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testdata/gentest/unary_type_test.proto",
}
