// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata/initdb/initdb.proto

package initdb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InsertAuthorRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Bio                  string   `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	FavouriteSection     string   `protobuf:"bytes,6,opt,name=favourite_section,json=favouriteSection,proto3" json:"favourite_section,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertAuthorRequest) Reset()         { *m = InsertAuthorRequest{} }
func (m *InsertAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*InsertAuthorRequest) ProtoMessage()    {}
func (*InsertAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c2f232df77707d6, []int{0}
}

func (m *InsertAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertAuthorRequest.Unmarshal(m, b)
}
func (m *InsertAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertAuthorRequest.Marshal(b, m, deterministic)
}
func (m *InsertAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertAuthorRequest.Merge(m, src)
}
func (m *InsertAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_InsertAuthorRequest.Size(m)
}
func (m *InsertAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertAuthorRequest proto.InternalMessageInfo

func (m *InsertAuthorRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertAuthorRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InsertAuthorRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *InsertAuthorRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InsertAuthorRequest) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *InsertAuthorRequest) GetFavouriteSection() string {
	if m != nil {
		return m.FavouriteSection
	}
	return ""
}

type InsertBlogRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AuthorId             uint32   `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertBlogRequest) Reset()         { *m = InsertBlogRequest{} }
func (m *InsertBlogRequest) String() string { return proto.CompactTextString(m) }
func (*InsertBlogRequest) ProtoMessage()    {}
func (*InsertBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c2f232df77707d6, []int{1}
}

func (m *InsertBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertBlogRequest.Unmarshal(m, b)
}
func (m *InsertBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertBlogRequest.Marshal(b, m, deterministic)
}
func (m *InsertBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertBlogRequest.Merge(m, src)
}
func (m *InsertBlogRequest) XXX_Size() int {
	return xxx_messageInfo_InsertBlogRequest.Size(m)
}
func (m *InsertBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertBlogRequest proto.InternalMessageInfo

func (m *InsertBlogRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertBlogRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *InsertBlogRequest) GetAuthorId() uint32 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

type InsertCommentRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId               uint32   `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertCommentRequest) Reset()         { *m = InsertCommentRequest{} }
func (m *InsertCommentRequest) String() string { return proto.CompactTextString(m) }
func (*InsertCommentRequest) ProtoMessage()    {}
func (*InsertCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c2f232df77707d6, []int{2}
}

func (m *InsertCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertCommentRequest.Unmarshal(m, b)
}
func (m *InsertCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertCommentRequest.Marshal(b, m, deterministic)
}
func (m *InsertCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertCommentRequest.Merge(m, src)
}
func (m *InsertCommentRequest) XXX_Size() int {
	return xxx_messageInfo_InsertCommentRequest.Size(m)
}
func (m *InsertCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertCommentRequest proto.InternalMessageInfo

func (m *InsertCommentRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertCommentRequest) GetPostId() uint32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *InsertCommentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InsertCommentRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type InsertPostRequest struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId             uint32               `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	BlogId               uint32               `protobuf:"varint,3,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	Section              string               `protobuf:"bytes,5,opt,name=section,proto3" json:"section,omitempty"`
	Subject              string               `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Draft                string               `protobuf:"bytes,7,opt,name=draft,proto3" json:"draft,omitempty"`
	Body                 string               `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InsertPostRequest) Reset()         { *m = InsertPostRequest{} }
func (m *InsertPostRequest) String() string { return proto.CompactTextString(m) }
func (*InsertPostRequest) ProtoMessage()    {}
func (*InsertPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c2f232df77707d6, []int{3}
}

func (m *InsertPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertPostRequest.Unmarshal(m, b)
}
func (m *InsertPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertPostRequest.Marshal(b, m, deterministic)
}
func (m *InsertPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertPostRequest.Merge(m, src)
}
func (m *InsertPostRequest) XXX_Size() int {
	return xxx_messageInfo_InsertPostRequest.Size(m)
}
func (m *InsertPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertPostRequest proto.InternalMessageInfo

func (m *InsertPostRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertPostRequest) GetAuthorId() uint32 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *InsertPostRequest) GetBlogId() uint32 {
	if m != nil {
		return m.BlogId
	}
	return 0
}

func (m *InsertPostRequest) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *InsertPostRequest) GetSection() string {
	if m != nil {
		return m.Section
	}
	return ""
}

func (m *InsertPostRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *InsertPostRequest) GetDraft() string {
	if m != nil {
		return m.Draft
	}
	return ""
}

func (m *InsertPostRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type InsertPostTagRequest struct {
	PostId               uint32   `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	TagId                uint32   `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertPostTagRequest) Reset()         { *m = InsertPostTagRequest{} }
func (m *InsertPostTagRequest) String() string { return proto.CompactTextString(m) }
func (*InsertPostTagRequest) ProtoMessage()    {}
func (*InsertPostTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c2f232df77707d6, []int{4}
}

func (m *InsertPostTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertPostTagRequest.Unmarshal(m, b)
}
func (m *InsertPostTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertPostTagRequest.Marshal(b, m, deterministic)
}
func (m *InsertPostTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertPostTagRequest.Merge(m, src)
}
func (m *InsertPostTagRequest) XXX_Size() int {
	return xxx_messageInfo_InsertPostTagRequest.Size(m)
}
func (m *InsertPostTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertPostTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertPostTagRequest proto.InternalMessageInfo

func (m *InsertPostTagRequest) GetPostId() uint32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *InsertPostTagRequest) GetTagId() uint32 {
	if m != nil {
		return m.TagId
	}
	return 0
}

type InsertTagRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertTagRequest) Reset()         { *m = InsertTagRequest{} }
func (m *InsertTagRequest) String() string { return proto.CompactTextString(m) }
func (*InsertTagRequest) ProtoMessage()    {}
func (*InsertTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c2f232df77707d6, []int{5}
}

func (m *InsertTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertTagRequest.Unmarshal(m, b)
}
func (m *InsertTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertTagRequest.Marshal(b, m, deterministic)
}
func (m *InsertTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertTagRequest.Merge(m, src)
}
func (m *InsertTagRequest) XXX_Size() int {
	return xxx_messageInfo_InsertTagRequest.Size(m)
}
func (m *InsertTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertTagRequest proto.InternalMessageInfo

func (m *InsertTagRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c2f232df77707d6, []int{6}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c2f232df77707d6, []int{7}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*InsertAuthorRequest)(nil), "initdb.InsertAuthorRequest")
	proto.RegisterType((*InsertBlogRequest)(nil), "initdb.InsertBlogRequest")
	proto.RegisterType((*InsertCommentRequest)(nil), "initdb.InsertCommentRequest")
	proto.RegisterType((*InsertPostRequest)(nil), "initdb.InsertPostRequest")
	proto.RegisterType((*InsertPostTagRequest)(nil), "initdb.InsertPostTagRequest")
	proto.RegisterType((*InsertTagRequest)(nil), "initdb.InsertTagRequest")
	proto.RegisterType((*EmptyResponse)(nil), "initdb.EmptyResponse")
	proto.RegisterType((*EmptyRequest)(nil), "initdb.EmptyRequest")
}

func init() { proto.RegisterFile("testdata/initdb/initdb.proto", fileDescriptor_4c2f232df77707d6) }

var fileDescriptor_4c2f232df77707d6 = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x4e, 0xdb, 0x30,
	0x14, 0x5e, 0x0b, 0x0d, 0xf4, 0x40, 0x19, 0x78, 0x45, 0xcb, 0x0a, 0xd2, 0x50, 0xae, 0x90, 0x26,
	0x5a, 0x89, 0x49, 0xfb, 0x95, 0xa6, 0x8d, 0x31, 0xa4, 0x5e, 0x6d, 0x0a, 0x68, 0x17, 0xbb, 0x41,
	0x4e, 0x6c, 0x82, 0xa1, 0x89, 0xb3, 0xf8, 0x84, 0x89, 0xd7, 0xda, 0x13, 0xed, 0x19, 0xf6, 0x04,
	0x93, 0xed, 0xb8, 0x4d, 0xaa, 0x45, 0xe2, 0x2a, 0xfe, 0xce, 0x39, 0xf9, 0xf2, 0x9d, 0xef, 0x1c,
	0x07, 0xf6, 0x91, 0x2b, 0x64, 0x14, 0xe9, 0x44, 0x64, 0x02, 0x59, 0x54, 0x3d, 0xc6, 0x79, 0x21,
	0x51, 0x12, 0xcf, 0xa2, 0xd1, 0xf3, 0x44, 0xca, 0x64, 0xc6, 0x27, 0x26, 0x1a, 0x95, 0x57, 0x13,
	0x14, 0x29, 0x57, 0x48, 0xd3, 0xdc, 0x16, 0x06, 0xbf, 0x3b, 0xf0, 0x64, 0x9a, 0x29, 0x5e, 0xe0,
	0xa7, 0x12, 0xaf, 0x65, 0x11, 0xf2, 0x9f, 0x25, 0x57, 0x48, 0xb6, 0xa0, 0x2b, 0x98, 0xdf, 0x39,
	0xe8, 0x1c, 0x0e, 0xc2, 0xae, 0x60, 0x64, 0x04, 0xeb, 0xa5, 0xe2, 0x45, 0x46, 0x53, 0xee, 0x77,
	0x0f, 0x3a, 0x87, 0xfd, 0x70, 0x8e, 0x75, 0x2e, 0xa7, 0x4a, 0xfd, 0x92, 0x05, 0xf3, 0x57, 0x6c,
	0xce, 0x61, 0x32, 0x84, 0x1e, 0x4f, 0xa9, 0x98, 0xf9, 0xab, 0x26, 0x61, 0x01, 0xd9, 0x86, 0x95,
	0x48, 0x48, 0xbf, 0x67, 0x62, 0xfa, 0x48, 0x5e, 0xc0, 0xce, 0x15, 0xbd, 0x93, 0x65, 0x21, 0x90,
	0x5f, 0x2a, 0x1e, 0xa3, 0x90, 0x99, 0xef, 0x99, 0xfc, 0xf6, 0x3c, 0x71, 0x6e, 0xe3, 0xc1, 0x77,
	0xd8, 0xb1, 0x9a, 0x4f, 0x66, 0x32, 0x69, 0x53, 0x3c, 0x84, 0x1e, 0x0a, 0x9c, 0x39, 0xb9, 0x16,
	0x90, 0x3d, 0xe8, 0x53, 0xd3, 0xe8, 0xa5, 0xb0, 0x62, 0x07, 0xe1, 0xba, 0x0d, 0x4c, 0x59, 0x90,
	0xc2, 0xd0, 0xf2, 0x7e, 0x96, 0x69, 0xca, 0x33, 0x6c, 0xa3, 0x7e, 0x0a, 0x6b, 0xb9, 0x54, 0xa8,
	0x29, 0xba, 0x26, 0xe8, 0x69, 0x38, 0x65, 0x84, 0xc0, 0xaa, 0x71, 0xc8, 0xba, 0x60, 0xce, 0xc4,
	0x87, 0xb5, 0xd8, 0xd2, 0x55, 0x1e, 0x38, 0x18, 0xfc, 0xed, 0xb8, 0x3e, 0xbe, 0x49, 0xd5, 0xfa,
	0xb1, 0x86, 0xe2, 0x6e, 0x53, 0xb1, 0x56, 0x12, 0xcd, 0x64, 0xb2, 0x68, 0xc6, 0xd3, 0x70, 0xca,
	0xc8, 0x5b, 0x80, 0xb8, 0xe0, 0x14, 0x39, 0xbb, 0x94, 0x99, 0xf9, 0xf0, 0xc6, 0xf1, 0x68, 0x6c,
	0xb7, 0x61, 0xec, 0xb6, 0x61, 0x7c, 0xe1, 0xb6, 0x21, 0xec, 0x57, 0xd5, 0x5f, 0x33, 0x2d, 0xd8,
	0x0d, 0xc0, 0x0e, 0xc8, 0x41, 0x93, 0x29, 0xa3, 0x1b, 0x1e, 0x63, 0x35, 0x1a, 0x07, 0xb5, 0xd9,
	0xac, 0xa0, 0x57, 0xe8, 0xaf, 0x59, 0xb3, 0x0d, 0xd0, 0x76, 0x44, 0x92, 0xdd, 0xfb, 0xeb, 0xd6,
	0x0e, 0x7d, 0x0e, 0xce, 0x9c, 0xc7, 0xba, 0xe7, 0x0b, 0x3a, 0x1f, 0x5f, 0xcd, 0xd3, 0x4e, 0xc3,
	0xd3, 0x5d, 0xf0, 0x90, 0x26, 0x8b, 0xe6, 0x7b, 0x48, 0x93, 0x29, 0x0b, 0x5e, 0xc1, 0xb6, 0xe5,
	0xa9, 0x71, 0x2c, 0x5b, 0xe7, 0xc6, 0xd1, 0x5d, 0x8c, 0x23, 0x78, 0x0c, 0x83, 0x2f, 0x69, 0x8e,
	0xf7, 0x21, 0x57, 0xb9, 0xcc, 0x14, 0x0f, 0xb6, 0x60, 0xb3, 0x0a, 0x18, 0x92, 0xe3, 0x3f, 0x2b,
	0xb0, 0x31, 0xcd, 0x04, 0x9e, 0xf3, 0xe2, 0x4e, 0xc4, 0x9c, 0xbc, 0x06, 0x4f, 0xc3, 0xd3, 0x13,
	0x32, 0x1c, 0x57, 0x77, 0xac, 0x5e, 0x3f, 0xda, 0x5d, 0x8a, 0x56, 0xb4, 0x8f, 0xc8, 0x29, 0x6c,
	0xd6, 0x6f, 0x16, 0xd9, 0x73, 0x85, 0xff, 0xb9, 0x6f, 0xed, 0x2c, 0x1f, 0x01, 0x16, 0xbb, 0x4e,
	0x9e, 0x35, 0x39, 0x6a, 0xfb, 0xdf, 0xce, 0x70, 0x06, 0x83, 0xc6, 0x56, 0x93, 0xfd, 0x26, 0x49,
	0x73, 0xd9, 0x1f, 0xa0, 0x44, 0x4f, 0x6e, 0x59, 0x49, 0x6d, 0x83, 0x1f, 0xa0, 0xa4, 0x9a, 0xfd,
	0xb2, 0x92, 0xe6, 0x4a, 0xb4, 0xf3, 0x7c, 0x80, 0xfe, 0x7c, 0xf6, 0xc4, 0x6f, 0x72, 0x3c, 0xe0,
	0xfd, 0x93, 0x77, 0x3f, 0xde, 0x24, 0x02, 0xaf, 0xcb, 0x68, 0x1c, 0xcb, 0x74, 0x72, 0x43, 0xe3,
	0x5b, 0x75, 0x7b, 0x63, 0xff, 0x91, 0xf1, 0x51, 0xc2, 0xb3, 0xa3, 0x94, 0xe6, 0x93, 0xa5, 0xff,
	0xeb, 0x7b, 0xfb, 0x88, 0x3c, 0x53, 0xf6, 0xf2, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x99,
	0xf1, 0xf4, 0x80, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InitServiceClient is the client API for InitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InitServiceClient interface {
	InitDB(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	InsertAuthor(ctx context.Context, in *InsertAuthorRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	InsertBlog(ctx context.Context, in *InsertBlogRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	InsertComment(ctx context.Context, in *InsertCommentRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	InsertPost(ctx context.Context, in *InsertPostRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	InsertPostTag(ctx context.Context, in *InsertPostTagRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	InsertTag(ctx context.Context, in *InsertTagRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type initServiceClient struct {
	cc *grpc.ClientConn
}

func NewInitServiceClient(cc *grpc.ClientConn) InitServiceClient {
	return &initServiceClient{cc}
}

func (c *initServiceClient) InitDB(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/initdb.InitService/InitDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) InsertAuthor(ctx context.Context, in *InsertAuthorRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/initdb.InitService/InsertAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) InsertBlog(ctx context.Context, in *InsertBlogRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/initdb.InitService/InsertBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) InsertComment(ctx context.Context, in *InsertCommentRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/initdb.InitService/InsertComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) InsertPost(ctx context.Context, in *InsertPostRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/initdb.InitService/InsertPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) InsertPostTag(ctx context.Context, in *InsertPostTagRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/initdb.InitService/InsertPostTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) InsertTag(ctx context.Context, in *InsertTagRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/initdb.InitService/InsertTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitServiceServer is the server API for InitService service.
type InitServiceServer interface {
	InitDB(context.Context, *EmptyRequest) (*EmptyResponse, error)
	InsertAuthor(context.Context, *InsertAuthorRequest) (*EmptyResponse, error)
	InsertBlog(context.Context, *InsertBlogRequest) (*EmptyResponse, error)
	InsertComment(context.Context, *InsertCommentRequest) (*EmptyResponse, error)
	InsertPost(context.Context, *InsertPostRequest) (*EmptyResponse, error)
	InsertPostTag(context.Context, *InsertPostTagRequest) (*EmptyResponse, error)
	InsertTag(context.Context, *InsertTagRequest) (*EmptyResponse, error)
}

// UnimplementedInitServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInitServiceServer struct {
}

func (*UnimplementedInitServiceServer) InitDB(ctx context.Context, req *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDB not implemented")
}
func (*UnimplementedInitServiceServer) InsertAuthor(ctx context.Context, req *InsertAuthorRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertAuthor not implemented")
}
func (*UnimplementedInitServiceServer) InsertBlog(ctx context.Context, req *InsertBlogRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertBlog not implemented")
}
func (*UnimplementedInitServiceServer) InsertComment(ctx context.Context, req *InsertCommentRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertComment not implemented")
}
func (*UnimplementedInitServiceServer) InsertPost(ctx context.Context, req *InsertPostRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertPost not implemented")
}
func (*UnimplementedInitServiceServer) InsertPostTag(ctx context.Context, req *InsertPostTagRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertPostTag not implemented")
}
func (*UnimplementedInitServiceServer) InsertTag(ctx context.Context, req *InsertTagRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertTag not implemented")
}

func RegisterInitServiceServer(s *grpc.Server, srv InitServiceServer) {
	s.RegisterService(&_InitService_serviceDesc, srv)
}

func _InitService_InitDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).InitDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/initdb.InitService/InitDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).InitDB(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_InsertAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).InsertAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/initdb.InitService/InsertAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).InsertAuthor(ctx, req.(*InsertAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_InsertBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).InsertBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/initdb.InitService/InsertBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).InsertBlog(ctx, req.(*InsertBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_InsertComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).InsertComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/initdb.InitService/InsertComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).InsertComment(ctx, req.(*InsertCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_InsertPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).InsertPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/initdb.InitService/InsertPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).InsertPost(ctx, req.(*InsertPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_InsertPostTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertPostTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).InsertPostTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/initdb.InitService/InsertPostTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).InsertPostTag(ctx, req.(*InsertPostTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_InsertTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).InsertTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/initdb.InitService/InsertTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).InsertTag(ctx, req.(*InsertTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InitService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "initdb.InitService",
	HandlerType: (*InitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitDB",
			Handler:    _InitService_InitDB_Handler,
		},
		{
			MethodName: "InsertAuthor",
			Handler:    _InitService_InsertAuthor_Handler,
		},
		{
			MethodName: "InsertBlog",
			Handler:    _InitService_InsertBlog_Handler,
		},
		{
			MethodName: "InsertComment",
			Handler:    _InitService_InsertComment_Handler,
		},
		{
			MethodName: "InsertPost",
			Handler:    _InitService_InsertPost_Handler,
		},
		{
			MethodName: "InsertPostTag",
			Handler:    _InitService_InsertPostTag_Handler,
		},
		{
			MethodName: "InsertTag",
			Handler:    _InitService_InsertTag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testdata/initdb/initdb.proto",
}
