// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/query.proto

package examples

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlogRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId             uint32   `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogRequest) Reset()         { *m = BlogRequest{} }
func (m *BlogRequest) String() string { return proto.CompactTextString(m) }
func (*BlogRequest) ProtoMessage()    {}
func (*BlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_358112bbf2967216, []int{0}
}

func (m *BlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogRequest.Unmarshal(m, b)
}
func (m *BlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogRequest.Marshal(b, m, deterministic)
}
func (m *BlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogRequest.Merge(m, src)
}
func (m *BlogRequest) XXX_Size() int {
	return xxx_messageInfo_BlogRequest.Size(m)
}
func (m *BlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlogRequest proto.InternalMessageInfo

func (m *BlogRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlogRequest) GetAuthorId() uint32 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

type BlogIdsRequest struct {
	Ids                  []uint32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Titles               []string `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogIdsRequest) Reset()         { *m = BlogIdsRequest{} }
func (m *BlogIdsRequest) String() string { return proto.CompactTextString(m) }
func (*BlogIdsRequest) ProtoMessage()    {}
func (*BlogIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_358112bbf2967216, []int{1}
}

func (m *BlogIdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogIdsRequest.Unmarshal(m, b)
}
func (m *BlogIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogIdsRequest.Marshal(b, m, deterministic)
}
func (m *BlogIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogIdsRequest.Merge(m, src)
}
func (m *BlogIdsRequest) XXX_Size() int {
	return xxx_messageInfo_BlogIdsRequest.Size(m)
}
func (m *BlogIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlogIdsRequest proto.InternalMessageInfo

func (m *BlogIdsRequest) GetIds() []uint32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *BlogIdsRequest) GetTitles() []string {
	if m != nil {
		return m.Titles
	}
	return nil
}

type BlogResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AuthorId             string   `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogResponse) Reset()         { *m = BlogResponse{} }
func (m *BlogResponse) String() string { return proto.CompactTextString(m) }
func (*BlogResponse) ProtoMessage()    {}
func (*BlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_358112bbf2967216, []int{2}
}

func (m *BlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogResponse.Unmarshal(m, b)
}
func (m *BlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogResponse.Marshal(b, m, deterministic)
}
func (m *BlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogResponse.Merge(m, src)
}
func (m *BlogResponse) XXX_Size() int {
	return xxx_messageInfo_BlogResponse.Size(m)
}
func (m *BlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlogResponse proto.InternalMessageInfo

func (m *BlogResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlogResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BlogResponse) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

type DetailedBlogResponse struct {
	BlogId               uint32   `protobuf:"varint,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	BlogTitle            string   `protobuf:"bytes,2,opt,name=blog_title,json=blogTitle,proto3" json:"blog_title,omitempty"`
	Author               *Author  `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Posts                []*Post  `protobuf:"bytes,4,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailedBlogResponse) Reset()         { *m = DetailedBlogResponse{} }
func (m *DetailedBlogResponse) String() string { return proto.CompactTextString(m) }
func (*DetailedBlogResponse) ProtoMessage()    {}
func (*DetailedBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_358112bbf2967216, []int{3}
}

func (m *DetailedBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailedBlogResponse.Unmarshal(m, b)
}
func (m *DetailedBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailedBlogResponse.Marshal(b, m, deterministic)
}
func (m *DetailedBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailedBlogResponse.Merge(m, src)
}
func (m *DetailedBlogResponse) XXX_Size() int {
	return xxx_messageInfo_DetailedBlogResponse.Size(m)
}
func (m *DetailedBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailedBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailedBlogResponse proto.InternalMessageInfo

func (m *DetailedBlogResponse) GetBlogId() uint32 {
	if m != nil {
		return m.BlogId
	}
	return 0
}

func (m *DetailedBlogResponse) GetBlogTitle() string {
	if m != nil {
		return m.BlogTitle
	}
	return ""
}

func (m *DetailedBlogResponse) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *DetailedBlogResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type Author struct {
	AuthorId               uint32   `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorUsername         string   `protobuf:"bytes,2,opt,name=author_username,json=authorUsername,proto3" json:"author_username,omitempty"`
	AuthorPassword         string   `protobuf:"bytes,3,opt,name=author_password,json=authorPassword,proto3" json:"author_password,omitempty"`
	AuthorEmail            string   `protobuf:"bytes,4,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	AuthorBio              string   `protobuf:"bytes,5,opt,name=author_bio,json=authorBio,proto3" json:"author_bio,omitempty"`
	AuthorFavouriteSection string   `protobuf:"bytes,6,opt,name=author_favourite_section,json=authorFavouriteSection,proto3" json:"author_favourite_section,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_358112bbf2967216, []int{4}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetAuthorId() uint32 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *Author) GetAuthorUsername() string {
	if m != nil {
		return m.AuthorUsername
	}
	return ""
}

func (m *Author) GetAuthorPassword() string {
	if m != nil {
		return m.AuthorPassword
	}
	return ""
}

func (m *Author) GetAuthorEmail() string {
	if m != nil {
		return m.AuthorEmail
	}
	return ""
}

func (m *Author) GetAuthorBio() string {
	if m != nil {
		return m.AuthorBio
	}
	return ""
}

func (m *Author) GetAuthorFavouriteSection() string {
	if m != nil {
		return m.AuthorFavouriteSection
	}
	return ""
}

type Post struct {
	PostId               uint32               `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	PostBlogId           uint32               `protobuf:"varint,2,opt,name=post_blog_id,json=postBlogId,proto3" json:"post_blog_id,omitempty"`
	PostAuthorId         uint32               `protobuf:"varint,3,opt,name=post_author_id,json=postAuthorId,proto3" json:"post_author_id,omitempty"`
	PostCreatedOn        *timestamp.Timestamp `protobuf:"bytes,4,opt,name=post_created_on,json=postCreatedOn,proto3" json:"post_created_on,omitempty"`
	PostSection          string               `protobuf:"bytes,5,opt,name=post_section,json=postSection,proto3" json:"post_section,omitempty"`
	PostSubject          string               `protobuf:"bytes,6,opt,name=post_subject,json=postSubject,proto3" json:"post_subject,omitempty"`
	Draft                string               `protobuf:"bytes,7,opt,name=draft,proto3" json:"draft,omitempty"`
	PostBody             string               `protobuf:"bytes,8,opt,name=post_body,json=postBody,proto3" json:"post_body,omitempty"`
	Comments             []*Comment           `protobuf:"bytes,9,rep,name=comments,proto3" json:"comments,omitempty"`
	Tags                 []*Tag               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_358112bbf2967216, []int{5}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetPostId() uint32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *Post) GetPostBlogId() uint32 {
	if m != nil {
		return m.PostBlogId
	}
	return 0
}

func (m *Post) GetPostAuthorId() uint32 {
	if m != nil {
		return m.PostAuthorId
	}
	return 0
}

func (m *Post) GetPostCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.PostCreatedOn
	}
	return nil
}

func (m *Post) GetPostSection() string {
	if m != nil {
		return m.PostSection
	}
	return ""
}

func (m *Post) GetPostSubject() string {
	if m != nil {
		return m.PostSubject
	}
	return ""
}

func (m *Post) GetDraft() string {
	if m != nil {
		return m.Draft
	}
	return ""
}

func (m *Post) GetPostBody() string {
	if m != nil {
		return m.PostBody
	}
	return ""
}

func (m *Post) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *Post) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Comment struct {
	CommentId            uint32   `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	CommentPostId        uint32   `protobuf:"varint,2,opt,name=comment_post_id,json=commentPostId,proto3" json:"comment_post_id,omitempty"`
	CommentName          string   `protobuf:"bytes,3,opt,name=comment_name,json=commentName,proto3" json:"comment_name,omitempty"`
	CommentText          string   `protobuf:"bytes,4,opt,name=comment_text,json=commentText,proto3" json:"comment_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_358112bbf2967216, []int{6}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetCommentId() uint32 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *Comment) GetCommentPostId() uint32 {
	if m != nil {
		return m.CommentPostId
	}
	return 0
}

func (m *Comment) GetCommentName() string {
	if m != nil {
		return m.CommentName
	}
	return ""
}

func (m *Comment) GetCommentText() string {
	if m != nil {
		return m.CommentText
	}
	return ""
}

type Tag struct {
	TagId                uint32   `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	TagName              string   `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_358112bbf2967216, []int{7}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTagId() uint32 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *Tag) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

type InsertAuthorRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Bio                  string   `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	FavouriteSection     string   `protobuf:"bytes,6,opt,name=favourite_section,json=favouriteSection,proto3" json:"favourite_section,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertAuthorRequest) Reset()         { *m = InsertAuthorRequest{} }
func (m *InsertAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*InsertAuthorRequest) ProtoMessage()    {}
func (*InsertAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_358112bbf2967216, []int{8}
}

func (m *InsertAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertAuthorRequest.Unmarshal(m, b)
}
func (m *InsertAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertAuthorRequest.Marshal(b, m, deterministic)
}
func (m *InsertAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertAuthorRequest.Merge(m, src)
}
func (m *InsertAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_InsertAuthorRequest.Size(m)
}
func (m *InsertAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertAuthorRequest proto.InternalMessageInfo

func (m *InsertAuthorRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertAuthorRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InsertAuthorRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *InsertAuthorRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InsertAuthorRequest) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *InsertAuthorRequest) GetFavouriteSection() string {
	if m != nil {
		return m.FavouriteSection
	}
	return ""
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_358112bbf2967216, []int{9}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BlogRequest)(nil), "examples.BlogRequest")
	proto.RegisterType((*BlogIdsRequest)(nil), "examples.BlogIdsRequest")
	proto.RegisterType((*BlogResponse)(nil), "examples.BlogResponse")
	proto.RegisterType((*DetailedBlogResponse)(nil), "examples.DetailedBlogResponse")
	proto.RegisterType((*Author)(nil), "examples.Author")
	proto.RegisterType((*Post)(nil), "examples.Post")
	proto.RegisterType((*Comment)(nil), "examples.Comment")
	proto.RegisterType((*Tag)(nil), "examples.Tag")
	proto.RegisterType((*InsertAuthorRequest)(nil), "examples.InsertAuthorRequest")
	proto.RegisterType((*EmptyResponse)(nil), "examples.EmptyResponse")
}

func init() { proto.RegisterFile("examples/query.proto", fileDescriptor_358112bbf2967216) }

var fileDescriptor_358112bbf2967216 = []byte{
	// 857 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0x41, 0x6f, 0xdb, 0x36,
	0x14, 0x8e, 0xec, 0xc4, 0xb1, 0x9f, 0x2d, 0x27, 0x65, 0xd3, 0x54, 0xf3, 0xd0, 0xcd, 0x11, 0x8a,
	0xcd, 0xc0, 0x10, 0xbb, 0x70, 0x31, 0x6c, 0xe8, 0xb0, 0x43, 0x93, 0x75, 0x98, 0x0f, 0xdb, 0x52,
	0xc5, 0x3b, 0x6c, 0x97, 0x80, 0x96, 0x18, 0x55, 0xa9, 0x24, 0xaa, 0x22, 0xd5, 0x25, 0x7f, 0x64,
	0xc7, 0xfd, 0x88, 0x1d, 0xf7, 0xb7, 0x06, 0xec, 0x3c, 0x90, 0x8f, 0x8c, 0xe4, 0xb4, 0x5e, 0x6f,
	0xe2, 0xf7, 0x7d, 0xef, 0x91, 0x7c, 0xef, 0x7b, 0x14, 0x1c, 0xb0, 0x6b, 0x9a, 0x15, 0x29, 0x13,
	0xb3, 0x37, 0x15, 0x2b, 0x6f, 0xa6, 0x45, 0xc9, 0x25, 0x27, 0x5d, 0x8b, 0x8e, 0x3e, 0x8d, 0x39,
	0x8f, 0x53, 0x36, 0xd3, 0xf8, 0xaa, 0xba, 0x9c, 0xc9, 0x24, 0x63, 0x42, 0xd2, 0xac, 0x40, 0xa9,
	0xff, 0x0c, 0xfa, 0x27, 0x29, 0x8f, 0x03, 0xf6, 0xa6, 0x62, 0x42, 0x92, 0x21, 0xb4, 0x92, 0xc8,
	0x73, 0xc6, 0xce, 0xc4, 0x0d, 0x5a, 0x49, 0x44, 0x3e, 0x86, 0x1e, 0xad, 0xe4, 0x2b, 0x5e, 0x5e,
	0x24, 0x91, 0xd7, 0xd2, 0x70, 0x17, 0x81, 0x45, 0xe4, 0x3f, 0x83, 0xa1, 0x8a, 0x5d, 0x44, 0xc2,
	0x86, 0xef, 0x43, 0x3b, 0x89, 0x84, 0xe7, 0x8c, 0xdb, 0x13, 0x37, 0x50, 0x9f, 0xe4, 0x10, 0x3a,
	0x32, 0x91, 0x29, 0x13, 0x5e, 0x6b, 0xdc, 0x9e, 0xf4, 0x02, 0xb3, 0xf2, 0x5f, 0xc2, 0x00, 0xf7,
	0x15, 0x05, 0xcf, 0x05, 0x7b, 0x67, 0xe3, 0x03, 0xd8, 0xd1, 0x4a, 0xbd, 0x69, 0x2f, 0xc0, 0xc5,
	0xfa, 0x71, 0xda, 0x9a, 0xa9, 0x8f, 0xf3, 0xa7, 0x03, 0x07, 0xdf, 0x31, 0x49, 0x93, 0x94, 0x45,
	0x6b, 0xb9, 0x1f, 0xc2, 0xee, 0x2a, 0xe5, 0xf1, 0xc5, 0xed, 0x06, 0x9d, 0x95, 0x3e, 0x36, 0x79,
	0x04, 0xa0, 0x89, 0xe6, 0x4e, 0x3d, 0x85, 0x2c, 0xf5, 0x6e, 0x13, 0xe8, 0x60, 0x72, 0xbd, 0x55,
	0x7f, 0xbe, 0x3f, 0xb5, 0x75, 0x9d, 0x3e, 0xd7, 0x78, 0x60, 0x78, 0xf2, 0x18, 0x76, 0x0a, 0x2e,
	0xa4, 0xf0, 0xb6, 0xc7, 0xed, 0x49, 0x7f, 0x3e, 0xac, 0x85, 0x67, 0x5c, 0xc8, 0x00, 0x49, 0xff,
	0x1f, 0x07, 0x3a, 0x18, 0xb8, 0x7e, 0x11, 0x67, 0xbd, 0xae, 0xe4, 0x73, 0xd8, 0x33, 0x64, 0x25,
	0x58, 0x99, 0xd3, 0xcc, 0x9e, 0x6d, 0x88, 0xf0, 0x2f, 0x06, 0x6d, 0x08, 0x0b, 0x2a, 0xc4, 0xef,
	0xbc, 0xb4, 0x45, 0x31, 0xc2, 0x33, 0x83, 0x92, 0x23, 0x18, 0x18, 0x21, 0xcb, 0x68, 0x92, 0x7a,
	0xdb, 0x5a, 0xd5, 0x47, 0xec, 0x85, 0x82, 0x54, 0x2d, 0x8c, 0x64, 0x95, 0x70, 0x6f, 0x07, 0x6b,
	0x81, 0xc8, 0x49, 0xc2, 0xc9, 0xd7, 0xe0, 0x19, 0xfa, 0x92, 0xbe, 0xe5, 0x55, 0x99, 0x48, 0x76,
	0x21, 0x58, 0x28, 0x13, 0x9e, 0x7b, 0x1d, 0x2d, 0x3e, 0x44, 0xfe, 0x7b, 0x4b, 0x9f, 0x23, 0xeb,
	0xff, 0xdb, 0x82, 0x6d, 0x55, 0x05, 0xd5, 0x06, 0x55, 0x87, 0x46, 0x1b, 0xd4, 0x72, 0x11, 0x91,
	0x31, 0x0c, 0x34, 0x61, 0x9b, 0x84, 0x3e, 0x03, 0x85, 0xa1, 0xbf, 0xc8, 0x63, 0x18, 0x6a, 0xc5,
	0x7a, 0xf3, 0xdd, 0x40, 0xc7, 0x3d, 0xb7, 0x75, 0x3b, 0x81, 0x3d, 0xad, 0x0a, 0x4b, 0x46, 0x25,
	0x8b, 0x2e, 0x78, 0xae, 0x2f, 0xda, 0x9f, 0x8f, 0xa6, 0x38, 0x06, 0x53, 0x3b, 0x06, 0xd3, 0xa5,
	0x1d, 0x83, 0xc0, 0x55, 0x21, 0xa7, 0x18, 0xf1, 0x73, 0xae, 0x2a, 0xa5, 0x73, 0xd8, 0xbb, 0x61,
	0x21, 0xfa, 0x0a, 0x33, 0x17, 0xaa, 0x25, 0xd5, 0xea, 0x8a, 0x85, 0xd2, 0x5c, 0x1f, 0x25, 0x08,
	0x29, 0xf7, 0x46, 0x25, 0xbd, 0x94, 0xde, 0x2e, 0xba, 0x57, 0x2f, 0x54, 0xd3, 0xf1, 0x9e, 0x3c,
	0xba, 0xf1, 0xba, 0xe8, 0x5e, 0x7d, 0x49, 0x1e, 0xdd, 0x90, 0x63, 0xe8, 0x86, 0x3c, 0xcb, 0x58,
	0x2e, 0x85, 0xd7, 0xd3, 0x2e, 0xba, 0x57, 0xbb, 0xe8, 0x14, 0x99, 0xe0, 0x56, 0x42, 0x8e, 0x60,
	0x5b, 0xd2, 0x58, 0x78, 0xa0, 0xa5, 0x6e, 0x2d, 0x5d, 0xd2, 0x38, 0xd0, 0x94, 0xff, 0x87, 0x03,
	0xbb, 0x26, 0x50, 0x75, 0xd7, 0x84, 0xd6, 0xe5, 0xef, 0x19, 0x64, 0x11, 0x91, 0xcf, 0x60, 0xcf,
	0xd2, 0xb6, 0x45, 0xd8, 0x04, 0xd7, 0xc0, 0x67, 0xd8, 0xa9, 0x23, 0x18, 0x58, 0x9d, 0xb6, 0x25,
	0xba, 0xad, 0x6f, 0xb0, 0x9f, 0x94, 0x27, 0x1b, 0x12, 0xc9, 0xae, 0xa5, 0xb5, 0x9a, 0xc1, 0x96,
	0xec, 0x5a, 0xfa, 0x5f, 0x41, 0x7b, 0x49, 0x63, 0xf2, 0x00, 0x3a, 0x92, 0x36, 0xa6, 0x72, 0x47,
	0x52, 0xd5, 0xeb, 0x8f, 0xa0, 0xab, 0xe0, 0x86, 0xed, 0x77, 0x25, 0x8d, 0x55, 0x6e, 0xff, 0x2f,
	0x07, 0xee, 0x2f, 0x72, 0xc1, 0x4a, 0xd3, 0xf3, 0x4d, 0xaf, 0xd6, 0x08, 0xba, 0x77, 0x26, 0xe7,
	0x76, 0xad, 0xb8, 0x3b, 0xc3, 0x72, 0xbb, 0x56, 0x6d, 0x6b, 0xce, 0x07, 0x2e, 0xd4, 0xa3, 0x56,
	0x8f, 0x84, 0xfa, 0x24, 0x5f, 0xc0, 0xbd, 0x4d, 0x53, 0xb0, 0x7f, 0x79, 0xd7, 0xff, 0x7b, 0xe0,
	0xbe, 0xc8, 0x0a, 0x79, 0x63, 0x9f, 0xa3, 0xf9, 0xdf, 0x2d, 0xd8, 0x57, 0xbe, 0x7e, 0xa9, 0x5e,
	0xec, 0x73, 0x56, 0xbe, 0x4d, 0x42, 0x46, 0xbe, 0x05, 0x38, 0x67, 0x29, 0x0b, 0xb5, 0xe3, 0xc9,
	0x83, 0xba, 0x9f, 0x8d, 0xd7, 0x79, 0x74, 0x78, 0x17, 0xc6, 0x8c, 0xfe, 0x16, 0x39, 0x85, 0x7e,
	0x1d, 0x2e, 0x88, 0xb7, 0x2e, 0xac, 0x5f, 0xe8, 0xcd, 0x29, 0x9e, 0x38, 0xe4, 0x47, 0x20, 0x98,
	0xa4, 0xf9, 0x8a, 0x6e, 0x3a, 0xcb, 0x27, 0x35, 0xfc, 0xbe, 0x47, 0xd7, 0xdf, 0x22, 0xe7, 0x70,
	0xff, 0xdd, 0x74, 0xff, 0x77, 0xb6, 0x0f, 0xa6, 0x7c, 0xe2, 0xcc, 0x7f, 0x05, 0x17, 0x1d, 0x60,
	0x0b, 0xf7, 0x03, 0x0c, 0x9a, 0x96, 0x20, 0x8f, 0xea, 0x24, 0xef, 0xb1, 0xca, 0xe8, 0x61, 0x4d,
	0xaf, 0x75, 0xc5, 0xdf, 0x3a, 0xf9, 0xf2, 0xb7, 0xa7, 0x71, 0x22, 0x5f, 0x55, 0xab, 0x69, 0xc8,
	0xb3, 0xd9, 0x15, 0x0d, 0x5f, 0x8b, 0xd7, 0x57, 0xf8, 0xe7, 0x0c, 0x8f, 0x63, 0x96, 0x1f, 0x67,
	0xb4, 0x98, 0xd9, 0xe8, 0x6f, 0xec, 0xc7, 0xaa, 0xa3, 0x15, 0x4f, 0xff, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x43, 0x72, 0xb9, 0xd1, 0x8b, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlogQueryServiceClient is the client API for BlogQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogQueryServiceClient interface {
	SelectBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*BlogResponse, error)
	SelectBlogs(ctx context.Context, in *BlogIdsRequest, opts ...grpc.CallOption) (BlogQueryService_SelectBlogsClient, error)
	SelectDetailedBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*DetailedBlogResponse, error)
	SelectDetailedBlogs(ctx context.Context, in *BlogIdsRequest, opts ...grpc.CallOption) (BlogQueryService_SelectDetailedBlogsClient, error)
}

type blogQueryServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogQueryServiceClient(cc *grpc.ClientConn) BlogQueryServiceClient {
	return &blogQueryServiceClient{cc}
}

func (c *blogQueryServiceClient) SelectBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*BlogResponse, error) {
	out := new(BlogResponse)
	err := c.cc.Invoke(ctx, "/examples.BlogQueryService/SelectBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogQueryServiceClient) SelectBlogs(ctx context.Context, in *BlogIdsRequest, opts ...grpc.CallOption) (BlogQueryService_SelectBlogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BlogQueryService_serviceDesc.Streams[0], "/examples.BlogQueryService/SelectBlogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &blogQueryServiceSelectBlogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlogQueryService_SelectBlogsClient interface {
	Recv() (*BlogResponse, error)
	grpc.ClientStream
}

type blogQueryServiceSelectBlogsClient struct {
	grpc.ClientStream
}

func (x *blogQueryServiceSelectBlogsClient) Recv() (*BlogResponse, error) {
	m := new(BlogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *blogQueryServiceClient) SelectDetailedBlog(ctx context.Context, in *BlogRequest, opts ...grpc.CallOption) (*DetailedBlogResponse, error) {
	out := new(DetailedBlogResponse)
	err := c.cc.Invoke(ctx, "/examples.BlogQueryService/SelectDetailedBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogQueryServiceClient) SelectDetailedBlogs(ctx context.Context, in *BlogIdsRequest, opts ...grpc.CallOption) (BlogQueryService_SelectDetailedBlogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BlogQueryService_serviceDesc.Streams[1], "/examples.BlogQueryService/SelectDetailedBlogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &blogQueryServiceSelectDetailedBlogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlogQueryService_SelectDetailedBlogsClient interface {
	Recv() (*DetailedBlogResponse, error)
	grpc.ClientStream
}

type blogQueryServiceSelectDetailedBlogsClient struct {
	grpc.ClientStream
}

func (x *blogQueryServiceSelectDetailedBlogsClient) Recv() (*DetailedBlogResponse, error) {
	m := new(DetailedBlogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlogQueryServiceServer is the server API for BlogQueryService service.
type BlogQueryServiceServer interface {
	SelectBlog(context.Context, *BlogRequest) (*BlogResponse, error)
	SelectBlogs(*BlogIdsRequest, BlogQueryService_SelectBlogsServer) error
	SelectDetailedBlog(context.Context, *BlogRequest) (*DetailedBlogResponse, error)
	SelectDetailedBlogs(*BlogIdsRequest, BlogQueryService_SelectDetailedBlogsServer) error
}

// UnimplementedBlogQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlogQueryServiceServer struct {
}

func (*UnimplementedBlogQueryServiceServer) SelectBlog(ctx context.Context, req *BlogRequest) (*BlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectBlog not implemented")
}
func (*UnimplementedBlogQueryServiceServer) SelectBlogs(req *BlogIdsRequest, srv BlogQueryService_SelectBlogsServer) error {
	return status.Errorf(codes.Unimplemented, "method SelectBlogs not implemented")
}
func (*UnimplementedBlogQueryServiceServer) SelectDetailedBlog(ctx context.Context, req *BlogRequest) (*DetailedBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectDetailedBlog not implemented")
}
func (*UnimplementedBlogQueryServiceServer) SelectDetailedBlogs(req *BlogIdsRequest, srv BlogQueryService_SelectDetailedBlogsServer) error {
	return status.Errorf(codes.Unimplemented, "method SelectDetailedBlogs not implemented")
}

func RegisterBlogQueryServiceServer(s *grpc.Server, srv BlogQueryServiceServer) {
	s.RegisterService(&_BlogQueryService_serviceDesc, srv)
}

func _BlogQueryService_SelectBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogQueryServiceServer).SelectBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.BlogQueryService/SelectBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogQueryServiceServer).SelectBlog(ctx, req.(*BlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogQueryService_SelectBlogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlogIdsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlogQueryServiceServer).SelectBlogs(m, &blogQueryServiceSelectBlogsServer{stream})
}

type BlogQueryService_SelectBlogsServer interface {
	Send(*BlogResponse) error
	grpc.ServerStream
}

type blogQueryServiceSelectBlogsServer struct {
	grpc.ServerStream
}

func (x *blogQueryServiceSelectBlogsServer) Send(m *BlogResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BlogQueryService_SelectDetailedBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogQueryServiceServer).SelectDetailedBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.BlogQueryService/SelectDetailedBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogQueryServiceServer).SelectDetailedBlog(ctx, req.(*BlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogQueryService_SelectDetailedBlogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlogIdsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlogQueryServiceServer).SelectDetailedBlogs(m, &blogQueryServiceSelectDetailedBlogsServer{stream})
}

type BlogQueryService_SelectDetailedBlogsServer interface {
	Send(*DetailedBlogResponse) error
	grpc.ServerStream
}

type blogQueryServiceSelectDetailedBlogsServer struct {
	grpc.ServerStream
}

func (x *blogQueryServiceSelectDetailedBlogsServer) Send(m *DetailedBlogResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _BlogQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "examples.BlogQueryService",
	HandlerType: (*BlogQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectBlog",
			Handler:    _BlogQueryService_SelectBlog_Handler,
		},
		{
			MethodName: "SelectDetailedBlog",
			Handler:    _BlogQueryService_SelectDetailedBlog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SelectBlogs",
			Handler:       _BlogQueryService_SelectBlogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SelectDetailedBlogs",
			Handler:       _BlogQueryService_SelectDetailedBlogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "examples/query.proto",
}

// InsertServiceClient is the client API for InsertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InsertServiceClient interface {
	InsertAuthor(ctx context.Context, in *InsertAuthorRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type insertServiceClient struct {
	cc *grpc.ClientConn
}

func NewInsertServiceClient(cc *grpc.ClientConn) InsertServiceClient {
	return &insertServiceClient{cc}
}

func (c *insertServiceClient) InsertAuthor(ctx context.Context, in *InsertAuthorRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/examples.InsertService/InsertAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsertServiceServer is the server API for InsertService service.
type InsertServiceServer interface {
	InsertAuthor(context.Context, *InsertAuthorRequest) (*EmptyResponse, error)
}

// UnimplementedInsertServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInsertServiceServer struct {
}

func (*UnimplementedInsertServiceServer) InsertAuthor(ctx context.Context, req *InsertAuthorRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertAuthor not implemented")
}

func RegisterInsertServiceServer(s *grpc.Server, srv InsertServiceServer) {
	s.RegisterService(&_InsertService_serviceDesc, srv)
}

func _InsertService_InsertAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsertServiceServer).InsertAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.InsertService/InsertAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsertServiceServer).InsertAuthor(ctx, req.(*InsertAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InsertService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "examples.InsertService",
	HandlerType: (*InsertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertAuthor",
			Handler:    _InsertService_InsertAuthor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/query.proto",
}
