// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: examples/query.proto

package examples

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"

	//protoc-gen-map packages
	bytes "bytes"
	context "context"
	sql "database/sql"
	sprig "github.com/Masterminds/sprig"
	mapper "github.com/jackskj/protoc-gen-map/mapper"
	mappertmpl "github.com/jackskj/protoc-gen-map/templates"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	log "log"
	sync "sync"
	template "text/template"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Code generated by protoc-gen-map. DO NOT EDIT.
// To Use:
// 1. Instantiate MapperServers with sql.DB connection
// 2. Register MapperServer as the gRPC service server
// 3. Begin serving

var EnumValueMaps = map[string]map[string]int32{
	"Section": map[string]int32{
		"cooking":      0,
		"painting":     1,
		"snowboarding": 3,
		"woodworking":  2,
	},
}

func init() {
	mapper.RegisterEnums(EnumValueMaps)
}

type BlogQueryServiceMapServer struct {
	DB                        *sql.DB
	SelectBlogMapper          *mapper.Mapper
	SelectBlogsMapper         *mapper.Mapper
	SelectDetailedBlogMapper  *mapper.Mapper
	SelectDetailedBlogsMapper *mapper.Mapper

	mapperGenMux sync.Mutex
}

func (m *BlogQueryServiceMapServer) SelectBlog(ctx context.Context, r *BlogRequest) (*BlogResponse, error) {
	sqlBuffer := &bytes.Buffer{}
	if err := sqlTemplate.ExecuteTemplate(sqlBuffer, "SelectBlog", r); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	rawSql := sqlBuffer.String()

	rows, err := m.DB.Query(rawSql)
	defer rows.Close()
	if err != nil {
		log.Printf("error executing query.\n BlogRequest request: %s \n,query: %s \n error: %s", r, rawSql, err)
		return nil, status.Error(codes.InvalidArgument, "request generated malformed query")
	}
	if m.SelectBlogMapper == nil {
		m.mapperGenMux.Lock()
		m.SelectBlogMapper, err = mapper.New(rows, &BlogResponse{})
		m.mapperGenMux.Unlock()
		if err != nil {
			log.Printf("error generating SelectBlogMapper: %s", err)
			return nil, status.Error(codes.Internal, "error generating BlogResponse mapping")
		}
		m.SelectBlogMapper.Log()
	}
	respMap := m.SelectBlogMapper.NewResponseMapping()
	if err := m.SelectBlogMapper.GetValues(rows, respMap); err != nil {
		log.Printf("error loading data for SelectBlog: %s", err)
		return nil, status.Error(codes.Internal, "error loading data")
	}
	if err := m.SelectBlogMapper.MapResponse(respMap); err != nil {
		log.Printf("error mappig SelectBlogMapper: %s", err)
		m.SelectBlogMapper.Error = nil
		return nil, status.Error(codes.Internal, "error mappig BlogResponse")
	}
	m.SelectBlogMapper.Log()
	if len(respMap.Responses) == 0 {
		//No Responses found
		return new(BlogResponse), nil
	} else {
		return respMap.Responses[0].(*BlogResponse), nil
	}

}

func (m *BlogQueryServiceMapServer) SelectBlogs(r *BlogIdsRequest, stream BlogQueryService_SelectBlogsServer) error {
	sqlBuffer := &bytes.Buffer{}
	if err := sqlTemplate.ExecuteTemplate(sqlBuffer, "SelectBlogs", r); err != nil {
		return status.Error(codes.InvalidArgument, err.Error())
	}
	rawSql := sqlBuffer.String()
	rows, err := m.DB.Query(rawSql)
	defer rows.Close()
	if err != nil {
		log.Printf("error executing query.\n BlogIdsRequest request: %s \n,query: %s \n error: %s", r, rawSql, err)
		return status.Error(codes.InvalidArgument, "request generated malformed query")
	}
	if m.SelectBlogsMapper == nil {
		m.mapperGenMux.Lock()
		m.SelectBlogsMapper, err = mapper.New(rows, &BlogResponse{})
		m.mapperGenMux.Unlock()
		if err != nil {
			log.Printf("error generating SelectBlogsMapper: %s", err)
			return status.Error(codes.Internal, "error generating BlogResponse mapping")
		}
		m.SelectBlogsMapper.Log()
	}
	respMap := m.SelectBlogsMapper.NewResponseMapping()
	if err := m.SelectBlogsMapper.GetValues(rows, respMap); err != nil {
		log.Printf("error loading data for SelectBlogs: %s", err)
		return status.Error(codes.Internal, "error loading data")
	}
	if err := m.SelectBlogsMapper.MapResponse(respMap); err != nil {
		log.Printf("error mappig SelectBlogsMapper: %s", err)
		m.SelectBlogsMapper.Error = nil
		return status.Error(codes.Internal, "error mappig BlogResponse")
	}
	m.SelectBlogsMapper.Log()
	for _, resp := range respMap.Responses {
		if err := stream.Send(resp.(*BlogResponse)); err != nil {
			return err
		}
	}
	return nil
}

func (m *BlogQueryServiceMapServer) SelectDetailedBlog(ctx context.Context, r *BlogRequest) (*DetailedBlogResponse, error) {
	sqlBuffer := &bytes.Buffer{}
	if err := sqlTemplate.ExecuteTemplate(sqlBuffer, "SelectDetailedBlog", r); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	rawSql := sqlBuffer.String()

	rows, err := m.DB.Query(rawSql)
	defer rows.Close()
	if err != nil {
		log.Printf("error executing query.\n BlogRequest request: %s \n,query: %s \n error: %s", r, rawSql, err)
		return nil, status.Error(codes.InvalidArgument, "request generated malformed query")
	}
	if m.SelectDetailedBlogMapper == nil {
		m.mapperGenMux.Lock()
		m.SelectDetailedBlogMapper, err = mapper.New(rows, &DetailedBlogResponse{})
		m.mapperGenMux.Unlock()
		if err != nil {
			log.Printf("error generating SelectDetailedBlogMapper: %s", err)
			return nil, status.Error(codes.Internal, "error generating DetailedBlogResponse mapping")
		}
		m.SelectDetailedBlogMapper.Log()
	}
	respMap := m.SelectDetailedBlogMapper.NewResponseMapping()
	if err := m.SelectDetailedBlogMapper.GetValues(rows, respMap); err != nil {
		log.Printf("error loading data for SelectDetailedBlog: %s", err)
		return nil, status.Error(codes.Internal, "error loading data")
	}
	if err := m.SelectDetailedBlogMapper.MapResponse(respMap); err != nil {
		log.Printf("error mappig SelectDetailedBlogMapper: %s", err)
		m.SelectDetailedBlogMapper.Error = nil
		return nil, status.Error(codes.Internal, "error mappig DetailedBlogResponse")
	}
	m.SelectDetailedBlogMapper.Log()
	if len(respMap.Responses) == 0 {
		//No Responses found
		return new(DetailedBlogResponse), nil
	} else {
		return respMap.Responses[0].(*DetailedBlogResponse), nil
	}

}

func (m *BlogQueryServiceMapServer) SelectDetailedBlogs(r *BlogIdsRequest, stream BlogQueryService_SelectDetailedBlogsServer) error {
	sqlBuffer := &bytes.Buffer{}
	if err := sqlTemplate.ExecuteTemplate(sqlBuffer, "SelectDetailedBlogs", r); err != nil {
		return status.Error(codes.InvalidArgument, err.Error())
	}
	rawSql := sqlBuffer.String()
	rows, err := m.DB.Query(rawSql)
	defer rows.Close()
	if err != nil {
		log.Printf("error executing query.\n BlogIdsRequest request: %s \n,query: %s \n error: %s", r, rawSql, err)
		return status.Error(codes.InvalidArgument, "request generated malformed query")
	}
	if m.SelectDetailedBlogsMapper == nil {
		m.mapperGenMux.Lock()
		m.SelectDetailedBlogsMapper, err = mapper.New(rows, &DetailedBlogResponse{})
		m.mapperGenMux.Unlock()
		if err != nil {
			log.Printf("error generating SelectDetailedBlogsMapper: %s", err)
			return status.Error(codes.Internal, "error generating DetailedBlogResponse mapping")
		}
		m.SelectDetailedBlogsMapper.Log()
	}
	respMap := m.SelectDetailedBlogsMapper.NewResponseMapping()
	if err := m.SelectDetailedBlogsMapper.GetValues(rows, respMap); err != nil {
		log.Printf("error loading data for SelectDetailedBlogs: %s", err)
		return status.Error(codes.Internal, "error loading data")
	}
	if err := m.SelectDetailedBlogsMapper.MapResponse(respMap); err != nil {
		log.Printf("error mappig SelectDetailedBlogsMapper: %s", err)
		m.SelectDetailedBlogsMapper.Error = nil
		return status.Error(codes.Internal, "error mappig DetailedBlogResponse")
	}
	m.SelectDetailedBlogsMapper.Log()
	for _, resp := range respMap.Responses {
		if err := stream.Send(resp.(*DetailedBlogResponse)); err != nil {
			return err
		}
	}
	return nil
}

type InsertServiceMapServer struct {
	DB                 *sql.DB
	InsertAuthorMapper *mapper.Mapper

	mapperGenMux sync.Mutex
}

func (m *InsertServiceMapServer) InsertAuthor(ctx context.Context, r *InsertAuthorRequest) (*EmptyResponse, error) {
	sqlBuffer := &bytes.Buffer{}
	if err := sqlTemplate.ExecuteTemplate(sqlBuffer, "InsertAuthor", r); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	rawSql := sqlBuffer.String()

	_, err := m.DB.Exec(rawSql)
	if err != nil {
		log.Printf("error executing query.\n InsertAuthorRequest request: %s \n,query: %s \n error: %s", r, rawSql, err)
		return nil, status.Error(codes.InvalidArgument, "request generated malformed query")
	}
	resp := EmptyResponse{}
	return &resp, nil

}

var sqlTemplate, _ = template.New("sqlTemplate").Funcs(sprig.TxtFuncMap()).Funcs(mappertmpl.Funcs()).Parse(`
{{ define "SelectBlog" }}
select
        id,
        title,
        author_id
from blog
where id = {{ .Id }} limit 1
{{ end }}


{{ define "SelectBlogs" }}
select
        id,
        title,
        author_id
from blog
        where id in (
        {{ .Ids | join " , " }}
        ) or
        title in (
        {{ .Titles | squoteall | join " , " }}
        )
{{ end }}


{{ define "SelectDetailedBlog" }}
        {{template "DetailedBlog" }}
        {{ if .Id }}
                where B.id = {{ .Id }}
        {{ else if .AuthorId }}
                where B.author_id = {{ .AuthorId }}
        {{ end }}
{{ end }}


{{ define "SelectDetailedBlogs" }}
        {{ template "DetailedBlog" }}
        where B.id in (
        {{ .Ids | join " , " }}
        ) or
        B.title in (
        {{ .Titles | squoteall | join " , " }}
        )
{{ end }}

{{ define "DetailedBlog" }}
select
        B.id                as  blog_id,
        B.title             as  blog_title,
        A.id                as  author_id,
        A.username          as  author_username,
        A.password          as  author_password,
        A.email             as  author_email,
        A.bio               as  author_bio,
        A.favourite_section as  author_favourite_section,
        P.id                as  post_id,
        P.blog_id           as  post_blog_id,
        P.author_id         as  post_author_id,
        P.created_on        as  post_created_on,
        P.section           as  post_section,
        P.subject           as  post_subject,
        P.draft             as  draft,
        P.body              as  post_body,
        C.id                as  comment_id,
        C.post_id           as  comment_post_id,
        C.comment           as  comment_text,
        T.id                as  tag_id,
        T.name              as  tag_name
from blog B
        left outer join author A    on  B.author_id = A.id
        left outer join post P      on  B.id = P.blog_id
        left outer join comment C   on  P.id = C.post_id
        left outer join post_tag PT on  PT.post_id = P.id
        left outer join tag T       on  PT.tag_id = T.id
{{ end }}


{{define "InsertAuthor" }}
INSERT INTO author
VALUES (
 {{ .Id }},
 {{ .Username | quote }},
 {{ .Password | quote }},
 {{ .Email | quote }},
 {{ .Bio | quote }},
 {{ .FavouriteSection | quote }}
);
{{end}}

`)
