package examples

import (
	"database/sql"
	"fmt"
	"google.golang.org/grpc"
	"net"
)

// Example code demonstrating how to create gRPC server with protoc-gen-map
//
// For an example on how to test your grpc servers, head over mapper/mapper_test.go setup()
func exampleServer() {

	// Define your DB connection, in this example, we are using postgres
	connStr := "postgres://postgres@localhost:5432/postgres"
	db, err := sql.Open("postgres", connStr)
	if err != nil {
		// error when connection to DB fails
	}

	// Define a port to listen
	myPort := 15009
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", myPort))

	//Create a new gRPC server
	grpcServer := grpc.NewServer()

	// Instantiate MapServer generated by protoc-gen-map with your DB connection.
	myBlogMapServer := BlogQueryServiceMapServer{DB: db}

	// Use the above server object as the gRPC service server
	RegisterBlogQueryServiceServer(grpcServer, &myBlogMapServer)

	// Determine whether to use TLS

	//Begin serving
	grpcServer.Serve(lis)
}
